### ISSUE TITLE
Changelog should have sections where appropriate

### ISSUE THREAD

**Issue by guyellis** [passport-next/passport-facebook#1]
@rwky - really appreciate the Changelog that you're maintaining.

Would it be possible have sections in there for `3.0` and future entries if appropriate:

- Breaking
- Bug fixes
- Features

**Comment by guyellis** [comment]
i.e. it's not obvious to me what the breaking changes were that warranted the major version bump. I'm guessing the first item did? Where there any other items that were breaking?

**Comment by rwky** [comment]
@guyellis I've updated the changelog splitting by MAJOR/MINOR/PATCH as per https://semver.org so the breaking changes are the MAJOR ones in this case 


  *  Made graphApiVersion a mandatory option @rwky
  *  Removed deprecated username field @rwky

(If anyone was actually using the username field FB would throw an error anyway)

**Comment by guyellis** [comment]
Thanks @rwky - also as an FYI if you add a "fixes #1" as part of the commit message then when you push/merge it to master it will automatically close the issue and tag the issue with the commit.

**Comment by rwky** [comment]
Yep I know I just forgot ;)
