### ISSUE TITLE
/version/ calls are not working for me?

### ISSUE THREAD

**Issue by simllll** [passport-next/passport-facebook#4]
I had to overwrite all endpoint urls to get this library working.

```
      authorizationURL: 'https://www.facebook.com/dialog/oauth',
      tokenURL: 'https://graph.facebook.com/oauth/access_token',
      profileURL: 'https://graph.facebook.com/me',
```
By default it adds the version of the aip between .com/ and the endpoint. e.g. https://graph.facebook.com/v3.1/oauth/access_token .. which does not exist?!

Anything wrong on my side?

Regards

**Comment by simllll** [comment]
I have the issue, 
it was the graphApiVersion parameter..it's very important that you use "vX.Y" there..or at least this format. (e.g. v3.1, v3.2,...) maybe add a check to see if the provided parametr is valid.

regards

**Comment by rwky** [comment]
:+1: good idea.
